### ISSUE TITLE
Hierarchical index/ subsampling issue

### ISSUE THREAD

**Issue by harpone** [tmbdev/webdataset#16]
Hi! First off, really great to bump into this project, seems awesome :)

I may have a bit of a problem though, because I need to sample 2 (or more) image/target frames per video clip. So images and target .npy files are of form `('{id}.{n}.jpg', '{id}.{n}.npy')` with multiple `n` values for each `id` (maybe 10 to 100).

I'm now actually first sampling a random `id`, then sampling 2 different `n`:s inside the dataset `.__getitem__()` method and then streaming the `(image, target)` pairs on demand from GCS.  There's lots of small files, which cause quite a bit of overhead, so I figured Webdataset could be a great solution for this.

But I'm not sure how to tackle this subsampling issue with Webdataset... should I define 1 shard per `id`? Something else?

EDIT: no 1 shard per `id` would clearly not work, since I don't want lots of data in a minibatch from the same shard. Hmm...

**Comment by harpone** [comment]
... or could this work? If there are lots of dataloader workers, each has a different shard loaded, then a minibatch would contain samples from all the different shards?

**Comment by tmbdev** [comment]
The simplest thing to do is to precompute the sampling strategy; you can even do that using your existing random access dataset. That is, if you have a strategy for generating the pairs of samples, just write many (even hundreds) epochs worth of sampled pairs to disk. Depending on the sizes of the clips, the number of clips, etc. this may be smaller, about the same, or larger than your original dataset. Performance-wise, this is usually the right thing to do even if it uses a lot more storage because WebDataset can utilize rotation storage over the network, instead of much more expensive local SSD storage.

If that doesn't work for some reason, you can use hybrid strategies. For example, you can split your original video clips either into shorter clips or into subsets of frames; you generate many clips/subsets, shuffle those clips/subsets, and then sample from those as before. In order to utilize I/O bandwidth efficiently, you can generate multiple such samples from each clip and then shuffle those in memory.

Let me illustrate a little more how this works. Let's say you're fine with splitting your video into 1 sec clips, and you  have generated "vidshards-as-clips-{000000..000999}.tar" as your shards. Your pipeline now looks something like this:

```Python
def generate_pairs(src, nsamples=20):
    for inputs, outputs in src:
        nframes, nchannels, h, w = inputs.shape
        assert nframes == 30
        assert len(outputs) == nframes
        for i in range(nsamples):
            frame1 = random.range(nframes)
            frame2 = frame1
            while frame2 == frame1:
                frame2 = random.range(nframes)
           yield inputs[frame1], outputs[frame1], inputs[frame2], outputs[frame2]

dataset =wds.Dataset(...).decode(my_video_decoder).pipe(generate_pairs).shuffle(10000)
```

So, for reading 30 frames of video, we generate 20 pairs of samples. Of course, those will be all from the same video ID, so we don't want them to end up in the same batch. By putting a large `shuffle` after the `generate_pairs`, that's prevented. Given the amount of CPU memory machines have, you can use pretty large shuffle values. 

This actually scales up pretty well even if you need much longer clips. Let's say you need 30 second clips. In that case, you probably want to generate 1000 training pairs from those clips to amortize the generation cost over the I/O cost. In that case, a shuffle buffer of 10000 may be too small to give you the randomization you need, you may want to go to 1 million. For large images, that may run you out of memory, but you can easily shuffle on local SSD instead of main memory (we have a disk shuffle filter, but it's currently not included in WebDataset; it's pretty simple to write, though).

In general, there is an intrinsic tradeoff between being able to access data efficiently and sequentially, while at the same time being able to shuffle sufficiently well for your particular training application. This requires some thought, but WebDataset tries to guide you in the right direction.

TODO: include disk_shuffle

**Comment by harpone** [comment]
OK thanks for the comprehensive reply!

I guess the first approach would work, although I'd really like to avoid creating a huge dataset... actually I already have pretty short clips, so I think the second approach could work. I wasn't quite sure how the shuffling works, but thanks for clarifying!

I'll try the second approach and will report back how it goes, but I'll close for now. Thanks a lot!

**Comment by harpone** [comment]
This approach is working great, thank you @tmbdev ! :)

FYI initially I'm getting very low percentage of frames from different clips (about 30 frames per clip), and it usually takes around 500 iterations or so to get >90% of frames to be from different clips, depending on the shuffle buffer length (indeed getting some OOM issues for ~100k size buffers when on a 40GiB RAM machine at least - can get more RAM though). But I can live with that. Really nice!

FYI having this issue now: #24

**Comment by jc-audet** [comment]
Hello!

I'm trying to do a similar thing, however, I'm having trouble finding the correct way to do it with the code refactoring that has happened since this issue. 

Given the same `generate_pairs` function, what would be the equivalent of the pipe function in the following dataset definition?

`dataset =wds.Dataset(...).decode(my_video_decoder).pipe(generate_pairs).shuffle(10000)`

Thank you in advance!

**Comment by tmbdev** [comment]
I believe the pipeline you just gave should still work.

**Comment by zzl221000** [comment]
> Hello @harpone and @tmbdev !
> 
> I'm trying to do a similar thing, however, I'm having trouble finding the correct way to do it with the code refactoring that has happened since this issue.
> 
> Given the same `generate_pairs` function, what would be the equivalent of the pipe function in the following dataset definition?
> 
> `dataset =wds.Dataset(...).decode(my_video_decoder).pipe(generate_pairs).shuffle(10000)`
> 
> Thank you in advance!

`pipe` rename to `compose`

**Comment by trancelestial** [comment]
Hi @tmbdev, I have a similar requirement as OP, and your comments are very insightful thank you! You mentioned shuffling on SSD, have you included such a shuffler in WebDataset or could you perhaps provide a code snippet on how that could be done?
