### ISSUE TITLE
What is the purpose of the library, if you have to download the whole dataset?

### ISSUE THREAD

**Issue by davidmoseler** [tmbdev/webdataset#40]
The imagenet example (https://github.com/tmbdev/pytorch-imagenet-wds) seems to demonstrate that the library is completely useless.

First of all, what is a "shard"? Why do I need to "shard" a dataset? What is this about, where is the documentation for that?

Second, how can a library called "WEB Dataset" demand that you download the dataset in order to "shard" it and only then use it?

I need to train a model with imagenet, but I do not have hard drive space to download it. It seems that webdataset doesn't help me at all. What does this says about multi-terabyte datasets? Either the example was horrible, or the library is very questionable in terms of achieving what it aims to achieve.

**Comment by tmbdev** [comment]
[Here](https://www.youtube.com/playlist?list=PL0dsKxFNMcX59napupGk3cNVzbpx3yU0_) is a YouTube playlist that explains how to use WebDataset and what to use it for. It explains why/when you want to shard, etc.

> The imagenet example (https://github.com/tmbdev/pytorch-imagenet-wds) seems to demonstrate that the library is completely useless.I need to train a model with imagenet, but I do not have hard drive space to download it.

We can't distribute pre-sharded versions of ImageNet because ImageNet is available only under license; that's why the example shows you how to shard it. The code example you found exists only as an illustration of how to modify the PyTorch ImageNet example, not as a good example of how to write ImageNet training code.

WebDataset can train without any local storage. We frequently use it that way when training in containers. We have pre-sharded data available for other datasets. For example, OpenImages is available at http://storage.googleapis.com/nvdata-openimages/openimages-train-{000000..000554}.tar  You can train against those shards directly over the Internet, or alternatively, you can copy them to a local webserver and then run one or more training jobs against that web server. Whether you should use remote servers, local servers, or local disk depends on how much storage and how much network bandwidth you have available; WebDataset (like web browsers) can use any such data source transparently.

Although there is a lot of documentation (in the docs/ subdirectory) and the library is fast and pretty mature, we have no simple turn-key examples available for end users. We'll try to add those over the next few months.
