### ISSUE TITLE
ShardWriter for numpy arrays

### ISSUE THREAD

**Issue by rmchurch** [tmbdev/webdataset#6]
Simple question: if I am using a custom Pytorch dataset that returns a few numpy arrays (read from HDF5 files), how should I setup ShardWriter? I get "no handler for data" when I pass in normally (encoder=True below), and "ValueError: data doesn't map to a bytes after encoding (<class 'numpy.ndarray'>)" when encoder=False. Looking through the code, it looks like tenbin should be used, I'm just not sure how to use it. Do the dictionary keys have to correspond to handler extensions? They aren't custom key names? What do I do for multiple numpy arrays?

```
with wds.ShardWriter('shards/shard-%06d.tar',maxcount=1000,encoder=False) as sink:
    for idx,(X,target,index,weight) in enumerate(dataset):
        sink.write({
            '__key__': "%06d"%index,
            'data': X,
            'target': target,
            'weight': weight
            })
```

**Comment by rmchurch** [comment]
I see now I have to add a ".ten" extension to the keys. Still, an error is thrown, and looking closer it appears due to the fact that tenbin.py returns a `bytearray`, but SharWriter expects a `bytes` type, and so throws an error. Should the check instead be `isinstance(v,(bytes,bytearray))`?

**Comment by tmbdev** [comment]
The most convenient and common way of writing tensors in this context is to use Python/Torch's pickle function. You get that by using the ".pyd" extension. Your ShardWriter should probably look like this:

```Python
with wds.ShardWriter('shards/shard-%06d.tar',maxcount=1000) as sink:
    for idx,(X,target,index,weight) in enumerate(dataset):
        sink.write({
            '__key__': "%06d"%index,
            'data.pyd': X,
            'target.pyd': dict(target=target, weight=weight)
            })
```

> Do the dictionary keys have to correspond to handler extensions?

In principle, you can use whatever you like for decoding. The default decoder uses standard file name extensions; only the last extension counts for decoding, but all extensions together are used as a key, so you can have multiple objects encoded the same way. Common extensions are:

- .jpg, png, ppm: images
- .pyd: Python/PyTorch pickle
- .json: JSON-encoded data
- .ten: custom fast tensor encoding (usually, .pyd is better)

>  get "no handler for data" when I pass in normally (encoder=True below)

Yes, that's because your "extensions" ("data", "target", "width") don't correspond to known file name extensions.

TODO:
- improve documentation
- better error messages

**Comment by tmbdev** [comment]
I've added several small example to the ShardWriter portion of the documentation that hopefully illustrate the different use cases a bit better.

**Comment by tmbdev** [comment]
The `.ten` and `.tb` extensions now work. However, in most cases, you should probably use `.pyd`.
