### ISSUE TITLE
Reading in two images

### ISSUE THREAD

**Issue by hey0** [tmbdev/webdataset#7]
Hello,
I have to a webdataset with entries of the following form:
- id.image.png
- id.depth.png
- id.intrinsics.pyd

The image is a RGB image and depth is a uint16 grayscale image.

How can I use .decode in way that I get a [H, W, C]-uint8 array for iamge and a [H, W]-uint16 array for depth?

**Comment by tmbdev** [comment]
The `.decode(...)` method is just a convenience method that handles the common cases automatically; you can just map the sample and decode each byte array explicitly:

```Python
def decode_sample(sample):
    return dict(
        image=PIL.Image.open(io.BytesIO(data["image.png"]),
        depth=PIL.Image.open(io.BytesIO(data["depth.png"]),
        intrinsics=torch.load(io.BytesIO(data["intrinsics.pyd"])
    )

dataset = wds.Dataset(url).map(decode_sample)
```

You also have the option of using a different extension, like ".png" and ".png16", and then just specify a new decoder for ".png16".

Still, I'll keep this open as a request for enhancement, since down the line, we may want to consider some extensions to the `.decode` mechanism:

- add test cases for 16bpp file names to the current `.decode`
- add 16 bit file name extensions for image types
- `.decode(..., overrides={...})`
- refactor autodecode.py and make the creation of new decoders easier

**Comment by tmbdev** [comment]
The `.decode` method now takes a list of decoder functions that are called in sequence. You can write the above code more simply now as:

```Python
    def decode16(key, data):
        if not key.endswith(".depth.png"):
            return None
       return np.array(PIL.Image.open(io.BytesIO(data)))

    dataset = wds.Dataset(url).map(decode16, "pil")
```
